name: Bug report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug, and what you expected instead.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Include relevant frontmatter (scribe-visualization and/ord scribe-note-* keys) if applicable.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
    validations:
      required: true
  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian version
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: true
      options:
        - Desktop (Windows)
        - Desktop (macOS)
        - Desktop (Linux)
        - Mobile (iOS)
        - Mobile (Android)
    validations:
      required: true
